local helper = require("tests.mod_helper")
assert(helper.double(21) == 42, "module function")
assert(helper.name == "mod_helper", "module field")
assert(require("tests.mod_helper") == helper, "require caches")
assert(package.loaded["tests.mod_helper"] == helper, "package.loaded")
assert(type(package.path) == "string", "package.path")
assert(type(package.searchpath("tests.mod_helper", package.path)) == "string", "searchpath")
local ok, err = pcall(require, "no.such.module")
assert(not ok and err:match("not found") ~= nil, "missing module message")
print("require: ok")
